# Generated by Django 4.2.23 on 2025-08-23 18:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas_objetivo', models.IntegerField(help_text='Número total de horas objetivo para el período', validators=[django.core.validators.MinValueValidator(1)])),
                ('horas_max_dia', models.IntegerField(default=8, help_text='Máximo de horas que se pueden registrar por día', validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=False)),
                ('año', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_feriados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Día Feriado',
                'verbose_name_plural': 'Días Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'activo'), name='unique_active_period_per_user'),
        ),
        migrations.AddConstraint(
            model_name='diaferiado',
            constraint=models.UniqueConstraint(fields=('fecha', 'usuario'), name='unique_holiday_per_user_date'),
        ),
    ]
