# Generated by Django 4.2.23 on 2025-08-23 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='horas_max_dia',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Máximo de horas que se pueden registrar por día (ej: 7.5, 8.0)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
