# Generated by Django 4.2.23 on 2025-08-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_change_horas_max_dia_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaferiado',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional del feriado', null=True),
        ),
        migrations.AddField(
            model_name='diaferiado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
