# Generated by Django 4.2.23 on 2025-08-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_descripcion_to_diaferiado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incremento_horas_default', models.DecimalField(choices=[(0.25, '15 minutos (0.25h)'), (0.5, '30 minutos (0.5h)'), (1.0, '1 hora (1.0h)')], decimal_places=2, default=0.5, help_text='Incremento por defecto para nuevos usuarios', max_digits=3)),
                ('horas_minimas_default', models.DecimalField(decimal_places=2, default=0.5, help_text='Mínimo de horas por defecto para nuevos usuarios', max_digits=3)),
                ('horas_maximas_default', models.DecimalField(decimal_places=2, default=12.0, help_text='Máximo de horas por defecto para nuevos usuarios', max_digits=4)),
                ('horas_max_dia_default', models.DecimalField(decimal_places=2, default=8.0, help_text='Máximo de horas por día por defecto', max_digits=4)),
                ('formato_fecha_default', models.CharField(choices=[('%d/%m/%Y', 'DD/MM/YYYY'), ('%m/%d/%Y', 'MM/DD/YYYY'), ('%Y-%m-%d', 'YYYY-MM-DD')], default='%d/%m/%Y', help_text='Formato de fecha por defecto para nuevos usuarios', max_length=20)),
                ('permitir_fines_semana', models.BooleanField(default=False, help_text='Permitir registro de horas en fines de semana')),
                ('validar_feriados', models.BooleanField(default=True, help_text='Validar automáticamente días feriados')),
                ('duracion_periodo_default', models.IntegerField(default=30, help_text='Duración por defecto de períodos en días')),
                ('nombre_sistema', models.CharField(default='Sistema de Gestión de Horas', help_text='Nombre del sistema', max_length=100)),
                ('version', models.CharField(default='1.0.0', help_text='Versión del sistema', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
