# Generated by Django 4.2.23 on 2025-08-23 18:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=1, help_text='Horas trabajadas (mínimo 0.5h, máximo 12h, incrementos de 0.5h)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('12.0'))])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de las actividades realizadas')),
                ('tipo_tarea', models.CharField(choices=[('tarea', 'Tarea'), ('reunion', 'Reunión')], default='tarea', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to='core.periodo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to='proyectos.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Hora',
                'verbose_name_plural': 'Registros de Horas',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha', 'usuario'], name='horas_regis_fecha_c2fb57_idx'), models.Index(fields=['proyecto', 'fecha'], name='horas_regis_proyect_4c96bf_idx'), models.Index(fields=['periodo', 'fecha'], name='horas_regis_periodo_31dc13_idx')],
            },
        ),
    ]
