# Generated by Django 4.2.23 on 2025-08-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON')], max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('filtros_aplicados', models.JSONField(blank=True, default=dict)),
                ('total_registros', models.IntegerField(default=0)),
                ('tamaño_archivo', models.IntegerField(default=0, help_text='Tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Exportación',
                'verbose_name_plural': 'Reportes de Exportación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separador_csv', models.CharField(choices=[(',', 'Coma (,)'), (';', 'Punto y coma (;)'), ('\t', 'Tabulación')], default=',', max_length=5)),
                ('incluir_encabezados', models.BooleanField(default=True)),
                ('formato_fecha', models.CharField(choices=[('%d/%m/%Y', 'DD/MM/YYYY'), ('%m/%d/%Y', 'MM/DD/YYYY'), ('%Y-%m-%d', 'YYYY-MM-DD')], default='%d/%m/%Y', max_length=20)),
                ('incluir_proyecto', models.BooleanField(default=True)),
                ('incluir_cliente', models.BooleanField(default=True)),
                ('incluir_descripcion', models.BooleanField(default=True)),
                ('incluir_tipo_tarea', models.BooleanField(default=True)),
                ('incluir_periodo', models.BooleanField(default=False)),
                ('agrupar_por_proyecto', models.BooleanField(default=False)),
                ('agrupar_por_fecha', models.BooleanField(default=False)),
                ('incluir_totales', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reporte',
            },
        ),
    ]
