# Generated by Django 4.2.23 on 2025-08-29 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0001_initial'),
    ]

    operations = [
        # Eliminar el modelo existente
        migrations.DeleteModel(
            name='ConfiguracionReporte',
        ),
        
        # Recrear el modelo con la nueva estructura
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_exportacion', models.CharField(choices=[('csv', 'CSV (Comma Separated Values)'), ('xlsx', 'Excel (XLSX)'), ('pdf', 'PDF')], default='csv', max_length=10)),
                ('separador_csv', models.CharField(choices=[(',', 'Coma (,)'), (';', 'Punto y coma (;)'), ('|', 'Pipe (|)')], default=',', max_length=5)),
                ('incluir_encabezados', models.BooleanField(default=True)),
                ('solo_activos', models.BooleanField(default=True)),
                ('columnas', models.JSONField(default=list, help_text='Lista de columnas a incluir: fecha, proyecto, horas, tipo_tarea, descripcion, cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo_defecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodo')),
                ('proyectos_defecto', models.ManyToManyField(blank=True, to='proyectos.proyecto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reporte',
            },
        ),
    ]
