# Generated by Django 4.2.23 on 2025-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_update_configuracion_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionreporte',
            name='separador_decimal',
            field=models.CharField(choices=[('.', 'Punto (.) - Formato internacional'), (',', 'Coma (,) - Formato europeo/español')], default='.', max_length=1),
        ),
    ]
