# Generated by Django 4.2.23 on 2025-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='horas_maximas',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Máximo de horas que se pueden registrar por entrada', max_digits=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='horas_minimas',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Mínimo de horas que se pueden registrar', max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='incremento_horas',
            field=models.DecimalField(choices=[(0.25, '15 minutos (0.25h)'), (0.5, '30 minutos (0.5h)'), (1.0, '1 hora (1.0h)')], decimal_places=2, default=0.5, help_text='Incremento mínimo para registro de horas', max_digits=3),
        ),
    ]
